spring.application.name=visit-service
server.port=8085

# Eureka Configuration (Step 27.3)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# PostgreSQL Configuration (Step 27.4)
spring.datasource.url=jdbc:postgresql://localhost:5432/livinglink_visit_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Actuator
management.endpoints.web.exposure.include=*

# Security Configuration (Step 27.7)
jwt.secret=livinglink-auth-service-secret-key-for-jwt-token-generation-2026
