spring.application.name=matching-service
server.port=8085

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

management.endpoints.web.exposure.include=*
jwt.secret=livinglink-auth-service-secret-key-for-jwt-token-generation-2026
